# Generated by Django 4.1.6 on 2023-03-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Номер телефона'),
        ),
    ]
