# Generated by Django 4.1.6 on 2023-02-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_book_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-name',), 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.RemoveField(
            model_name='reader',
            name='book_list',
        ),
        migrations.AddField(
            model_name='reader',
            name='book_list',
            field=models.ManyToManyField(related_name='books', to='core.book', verbose_name='Список книг'),
        ),
    ]
