# Generated by Django 4.1.6 on 2023-02-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_book_options_remove_reader_book_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='book_list',
            field=models.ManyToManyField(null=True, related_name='books', to='core.book', verbose_name='Список книг'),
        ),
    ]
