# Generated by Django 4.1.6 on 2023-02-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_reader_book_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='book_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='books', to='core.book', verbose_name='Список книг'),
        ),
    ]
