# Generated by Django 4.1.6 on 2023-03-02 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_reader_book_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('surname', 'name'), 'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
    ]
