# Generated by Django 4.1.6 on 2023-03-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='book_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='books', to='core.book', verbose_name='Список книг'),
        ),
    ]
